### ISSUE TITLE
How do I create new presentation?

### ISSUE THREAD

**Issue by rawaludin** [Enteleform/ST_SublimeSlides#1]
I like the idea of this package. Have read through the readme, but I still can't get how to create my first presentation adding slide into it. Where could I find the explanation??

**Comment by Enteleform** [comment]
@rahmatawaludin 

To get started, you have to do 2 things:  
**1:** Add the file type you want to use @ [SlideNav.sublime-settings](https://github.com/Enteleform/ST_SlideNav/blob/master/SlideNav.sublime-settings) / `Comment Characters`
- Make sure to set up your user preferences by copying the text from  
  `Preferences / Package Settings / SlideNav / Settings - Default`  
  to  
  `Preferences / Package Settings / SlideNav / Settings - User`

**2:** Add one or more slides @ your presentation document using the `Insert_Slide` command:
- Default Hotkey : <kbd>ctrl</kbd>+<kbd>super</kbd>+<kbd>alt</kbd>+<kbd>.</kbd>
- Slides are automatically created in between the inserted headers

## Examples:

### @ [SlideNav.sublime-settings](https://github.com/Enteleform/ST_SlideNav/blob/master/SlideNav.sublime-settings) / `Comment Characters`

```
    "comment_characters":
        {

            "python":
                {
                    "extension":     "py",
                    "comment_start": "#",
                    "comment_end":   "#",
                },

        },
```

### @ Presentation.py
- type `Slide 1` and `Slide 2` on two separate lines, place a cursor on each line, & run the `Insert_Slide` command.
- add your desired content in between the Slide Headers

```
#▌▓▓▓▓▓   Slide 1   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌#


    This content
    will be shown
    in Slide 1


#▌▓▓▓▓▓   Slide 2   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌#


    This content
    will be shown
    in Slide 2


```

After you create your first slides, you will be able to use the `Navigate Slides` command
Default Hotkeys : <kbd>ctrl</kbd>+<kbd>super</kbd>+<kbd>alt</kbd>+<kbd>=</kbd> & <kbd>ctrl</kbd>+<kbd>super</kbd>+<kbd>alt</kbd>+<kbd>-</kbd>

**Comment by Enteleform** [comment]
@rahmatawaludin 

I just wrote an interactive tutorial document.

Check it out if you still have any questions:
[[SlideNav] Tutorial](https://github.com/Enteleform/ST_SlideNav/blob/master/Tutorial/%5BSlideNav%5D%20Tutorial.py)
